apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
  name: hello-world-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-server
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-world-server
    spec:
      containers:
        - image: yashpandit4u/golang-echo-server:0.4
          name: golang-echo-server
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
status: {}
